---

- name: Install Dependencies
  apt: pkg={{ item }}
  with_items:
    - postgresql-9.6
    - postgresql-contrib-9.6
    - python-psycopg2
    - acl

- name: Mount /var/tmp with acl
  shell: "sudo /bin/mount -t tmpfs tmpfs /var/tmp"
  when: inventory_hostname in groups['dbmaster']


- name: Enable service postgresql
  systemd:
    name: postgresql
    enabled: yes

- name: Create main directory
  file:
    path: /var/lib/postgresql/9.6/main/archive/
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  when: inventory_hostname in groups['dbmaster']

- name: Copy postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/9.6/main/postgresql.conf

- name: Copy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/9.6/main/pg_hba.conf

- name: Copy pass file
  template:
    src: .pgpass.j2
    dest: /var/tmp/.pgpass
    owner: postgres
    group: postgres
    mode: 0600


- name: Restart postgres
  systemd:
    state: restarted
    name: postgresql

- name: Allow admin become postgres
  template:
    src: su.j2
    dest: /etc/pam.d/su

- name: Create DB User for replication
  become: true
  become_user: postgres
  postgresql_user:
    name: "replica"
    password: "replica123"
    role_attr_flags: REPLICATION
  when: inventory_hostname in groups['dbmaster']


- name: Stop postgres dbslave
  systemd:
    state: stopped
    name: postgresql
  when: inventory_hostname in groups['dbslave']

- name: Clean main directory
  shell: mv /var/lib/postgresql/9.6/main /var/lib/postgresql/9.6/main-bkp
  ignore_errors: True
  when: inventory_hostname in groups['dbslave']

- name: Create main directory
  file:
    path: /var/lib/postgresql/9.6/main
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  when: inventory_hostname in groups['dbslave']

- name: Copy data from Master to Slave
  become: True
  become_user: postgres
  shell: /usr/bin/pg_basebackup -h dbmaster -w -U replica -D /var/lib/postgresql/9.6/main -P --xlog
  environment:
    PGPASSFILE: "/var/tmp/.pgpass"
  when: inventory_hostname in groups['dbslave']

- name: Copy recovery.conf on dbslave
  template:
    src: recovery.conf.j2
    dest: /var/lib/postgresql/9.6/main/recovery.conf
  when: inventory_hostname in groups['dbslave']

- name: Star postgres dbslave
  systemd:
    state: started
    name: postgresql
  when: inventory_hostname in groups['dbslave']

- name: create DB blacklisted
  become: true
  become_user: postgres
  postgresql_db:
    name: blacklisted
  when: inventory_hostname in groups['dbmaster']

- name: create DB user black
  become: true
  become_user: postgres
  postgresql_user:
    name: "black"
    password: "black123"
    role_attr_flags: SUPERUSER,LOGIN
  when: inventory_hostname in groups['dbmaster']
