---

- name: Install Dependencies
  apt:
    name: ['postgresql-9.6', 'postgresql-contrib-9.6', 'python-psycopg2', 'acl']

- name: Mount /var/tmp with acl
  shell: "sudo /bin/mount -t tmpfs tmpfs /var/tmp"
  tags:
    - notest

- name: Enable service postgresql
  systemd:
    name: postgresql
    enabled: yes
  tags:
    - notest

- name: Create main directory
  file:
    path: /var/lib/postgresql/9.6/main/archive/
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Copy postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/9.6/main/postgresql.conf

- name: Copy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/9.6/main/pg_hba.conf

- name: Restart postgres
  systemd:
    state: restarted
    name: postgresql
  tags:
    - notest

- name: Allow admin become postgres
  template:
    src: su.j2
    dest: /etc/pam.d/su

- name: Create DB User for replication
  become: true
  become_user: postgres
  postgresql_user:
    name: "replica"
    password: "replica123"
    role_attr_flags: REPLICATION
  tags:
    - notest

- name: create DB blacklisted
  become: true
  become_user: postgres
  postgresql_db:
    name: blacklisted
  tags:
    - notest

- name: create DB user black
  become: true
  become_user: postgres
  postgresql_user:
    name: "black"
    password: "black123"
    role_attr_flags: SUPERUSER
  tags:
    - notest
