---
- name: install unzip
  apt:
    name: unzip

- name: Install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
    dest: /bin/
    remote_src: yes

- name: Terraform Apply
  terraform:
    project_path: "{{ playbook_dir }}/terraform/"
    state: "present"
    variables:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      security_group: "{{ aws_security_group }}"
      subnet_id: "{{ aws_subnet_id }}"
      key_pair: "{{ aws_key_pair }}"
      region: "{{ region }}"
  register: tf_output
  tags:
    - notest

- name: Update inventory
  add_host:
    hostname: "{{ item['ip'] }}"
    groups:
      - "{{ item['group'] }}"
  with_items:
    - { ip: "{{ tf_output['outputs']['app1_ip']['value'] }}", group: "app" }
    - { ip: "{{ tf_output['outputs']['dbmaster_ip']['value'] }}", group: "dbmaster"}
    - { ip: "{{ tf_output['outputs']['dbslave_ip']['value'] }}", group: "dbslave" }
  tags:
    - notest

- name: Set Facts
  set_fact:
     app1_private_ip: "{{ tf_output['outputs']['app1_private_ip']['value'] }}"
     dbmaster_private_ip: "{{ tf_output['outputs']['dbmaster_private_ip']['value'] }}"
     dbslave_private_ip: "{{ tf_output['outputs']['dbslave_private_ip']['value'] }}"
  tags:
    - notest
